# https://travis-ci.org/#!/translate/virtaal
language: python
python:
  - 2.5
  - 2.6
  - 2.7
install:
  - pip install --use-mirrors translate-toolkit
  - pip install --use-mirrors python-Levenshtein
  - pip install --use-mirrors lxml
  - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors simplejson; fi
  - pip install --use-mirrors pycurl
  - sudo apt-get install pygtk
script:
  - python setup.py install
notifications:
  email:
    on_failure: change
    on_success: change
