# https://travis-ci.org/#!/translate/virtaal
language: python
python:
  - 2.6
  - 2.7
install:
  - pip install --use-mirrors translate-toolkit
  - pip install --use-mirrors python-Levenshtein
  - pip install --use-mirrors lxml
  - pip install --use-mirrors pycurl
  - sudo apt-get install python-gtk2
script:
  - python setup.py install
notifications:
  email:
    on_failure: change
    on_success: change
